#!/bin/bash

HERE=`pwd`

mkdir -p ../../conf.d
ln -s ../../conf.d $HERE

mkdir -p ../../certbot
ln -s ../../certbot $HERE

mkdir -p ../../logs
ln -s ../../logs $HERE

mkdir -p ../../../site/current/public/
ln -s ../../../site/current/public/ public-siteperso

mkdir -p ../../../docker-wordpress/current/wordpress-web/
ln -s ../../../docker-wordpress/current/wordpress-web/ public-wordpress

mkdir -p ../../../network/current/server/public/
ln -s ../../../network/current/server/public/ public-network-backend

mkdir -p ../../../network/current/client/assets/
ln -s ../../../network/current/client/assets/ public-network-frontend

echo "Symbolic links for conf.d, logs and public folders ready"